name: systems_intro
channels:
  - damianavila82
  - conda-forge
  - defaults
dependencies:
  - anaconda-client=1.6.5=py_0
  - asn1crypto=0.22.0=py36_0
  - ca-certificates=2017.11.5=0
  - certifi=2017.11.5=py36_0
  - cffi=1.11.2=py36_0
  - chardet=3.0.4=py36_0
  - clyent=1.2.2=py36_0
  - cryptography=2.1.4=py36_0
  - idna=2.6=py36_1
  - ipywidgets=7.1.0=py36_0
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.1.0=py36_0
  - openssl=1.0.2n=vc14_0
  - pycparser=2.18=py36_0
  - pyopenssl=17.2.0=py36_0
  - pysocks=1.6.8=py_0
  - pyyaml=3.12=py36_1
  - requests=2.18.4=py36_1
  - urllib3=1.22=py36_0
  - widgetsnbextension=3.1.0=py36_0
  - yaml=0.1.7=vc14_0
  - rise=5.1.0=py36_1
  - _nb_ext_conf=0.4.0=py36_1
  - bleach=2.1.1=py36h834942a_0
  - colorama=0.3.9=py36h029ae33_0
  - decorator=4.1.2=py36he63a57b_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - html5lib=1.0.1=py36h047fa9f_0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2018.0.0=hd92c6cd_8
  - ipykernel=4.7.0=py36h2f9c1c0_0
  - ipython=6.2.1=py36h9cf0123_1
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - jedi=0.11.0=py36_2
  - jinja2=2.10=py36h292fed1_0
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter_client=5.1.0=py36h9902a9a_0
  - jupyter_core=4.4.0=py36h56e9d50_0
  - markupsafe=1.0=py36h0e26971_1
  - mistune=0.8.1=py36h007b88b_0
  - mkl=2018.0.1=h2108138_4
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - nbpresent=3.0.2=py36_0
  - notebook=5.2.2=py36hc48260a_0
  - numpy=1.13.3=py36ha320f96_0
  - pandas=0.22.0=py36h6538335_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.1.1=py36hae3edee_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pip=9.0.1=py36h226ae91_4
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - pygments=2.2.0=py36hb010967_0
  - python=3.6.3=h3b118a2_4
  - python-dateutil=2.6.1=py36h509ddcb_1
  - pytz=2017.3=py36h1d3fa6b_0
  - pyzmq=16.0.3=py36he714bf5_0
  - setuptools=36.5.0=py36h65f9e6e_0
  - simplegeneric=0.8.1=py36heab741f_0
  - six=1.11.0=py36h4db2310_1
  - testpath=0.3.1=py36h2698cfe_0
  - tornado=4.5.2=py36h57f6048_0
  - traitlets=4.3.2=py36h096827d_0
  - vc=14=h2379b0c_2
  - vs2015_runtime=14.0.25123=hd4c4e62_2
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36h67c50ae_1
  - wheel=0.30.0=py36h6c3ec14_1
  - wincertstore=0.2=py36h7fe50ca_0
prefix: C:\Users\kmongeon\Anaconda3\envs\systems_intro

